server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yue-zi-xuan/springcloud-config.git

#          GitHub上面的git仓库名字
          ###搜索目录
          search-paths:
            - springcloud-config
          username: 1973569840@qq.com
          password: 5757124avc
            ####读取分支
          label: main
  rabbitmq:
    host: 39.106.45.163
    port: 5672
    username: user
    password: password
    virtual-host: /



#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: false
    register-with-eureka: false


##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'



